# Generated by Django 6.1.1 on 2026-10-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='parameter',
            new_name='adventure_setting',
        ),
    ]
